'use client';
import AppShell from '@/components/AppShell';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {BookOpen,Check,X} from 'lucide-react';
import {fetchMyWatches} from '@/lib/supabase';
import {acceptWatchTransfer,fetchTransfers,rejectWatchTransfer} from '@/lib/watch-passport';
import {getSession} from '@/lib/supabase';
export default function PassportHub(){const[watches,setWatches]=useState<any[]>([]),[transfers,setTransfers]=useState<any[]>([]),[msg,setMsg]=useState('');const me=getSession()?.user.id;async function load(){try{const[w,t]=await Promise.all([fetchMyWatches(),fetchTransfers()]);setWatches(w);setTransfers(t)}catch(e){setMsg(e instanceof Error?e.message:'Errore')}}useEffect(()=>{load()},[]);async function act(id:string,accept:boolean){try{if(accept)await acceptWatchTransfer(id);else await rejectWatchTransfer(id);setMsg(accept?'Trasferimento accettato.':'Trasferimento rifiutato.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Errore')}}return <AppShell><div className="pagehead"><div><div className="eyebrow">WATCH PASSPORT</div><h1>Passaporti digitali</h1><p className="muted">Storia, manutenzioni, modifiche e passaggi di proprietà dei tuoi orologi.</p></div><BookOpen size={34}/></div>{msg&&<p className="form-message">{msg}</p>}{transfers.some(t=>t.to_user_id===me&&t.status==='pending')&&<section className="card" style={{marginBottom:18}}><h2>Trasferimenti in arrivo</h2>{transfers.filter(t=>t.to_user_id===me&&t.status==='pending').map(t=><div className="person-row" key={t.id}><div className="avatar"><BookOpen size={18}/></div><div><b>{t.watches?.brand} {t.watches?.model}</b><div className="muted">Richiesta di trasferimento proprietà</div></div><div className="offer-actions" style={{marginLeft:'auto'}}><button className="btn primary" onClick={()=>act(t.id,true)}><Check size={15}/> Accetta</button><button className="btn" onClick={()=>act(t.id,false)}><X size={15}/> Rifiuta</button></div></div>)}</section>}<div className="watch-grid">{watches.map(w=><Link href={`/watch/${w.id}/passport`} className="watch-card" key={w.id}><img src={w.image||'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=800&q=80'} alt=""/><div className="watch-card-body"><div className="eyebrow">WATCH PASSPORT</div><h3>{w.brand} {w.model}</h3><p className="muted">{w.reference||'Referenza non inserita'}</p><span className="btn primary">Apri passaporto</span></div></Link>)}</div></AppShell>}
