'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Check,ShieldCheck,UserPlus,X} from 'lucide-react';
import {fetchGuardianLinks,fetchGuardianWatches,inviteGuardianByUsername,respondGuardianLink,revokeGuardianLink} from '@/lib/minor-safety';
import {getSession} from '@/lib/supabase';

export default function GuardianPanel({accountMode}:{accountMode?:string}){
 const me=getSession()?.user.id;const[links,setLinks]=useState<any[]>([]);const[profiles,setProfiles]=useState<any[]>([]);const[watches,setWatches]=useState<any[]>([]);const[username,setUsername]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);
 async function load(){try{const d=await fetchGuardianLinks();setLinks(d.links);setProfiles(d.profiles);if(accountMode!=='minor_basic')setWatches(await fetchGuardianWatches())}catch(e){setMsg(e instanceof Error?e.message:'Errore')}}
 useEffect(()=>{load()},[accountMode]);
 const byId=useMemo(()=>new Map(profiles.map(p=>[p.id,p])),[profiles]);
 async function invite(e:React.FormEvent){e.preventDefault();if(!username.trim())return;setBusy(true);try{await inviteGuardianByUsername(username);setUsername('');setMsg('Richiesta inviata. L’adulto dovrà accettare la responsabilità dal proprio profilo.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Impossibile inviare la richiesta')}finally{setBusy(false)}}
 async function respond(id:string,accept:boolean){setBusy(true);try{await respondGuardianLink(id,accept);setMsg(accept?'Collegamento accettato. Le attività Marketplace effettuate per il minore restano sotto la responsabilità dell’adulto.':'Richiesta rifiutata.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Errore')}finally{setBusy(false)}}
 async function revoke(id:string){if(!confirm('Revocare questo collegamento?'))return;await revokeGuardianLink(id);await load()}
 if(accountMode==='minor_basic')return <section className="card guardian-panel"><div className="settings-title-row"><div><div className="eyebrow">PROTEZIONE MINORI</div><h2>Adulto responsabile</h2><p className="muted">Puoi nominare un adulto già registrato su WatchVault. L’adulto potrà consultare la tua collezione e, dal proprio account, gestire eventuali vendite Marketplace sotto la propria responsabilità.</p></div><ShieldCheck/></div><form onSubmit={invite} className="guardian-invite"><div className="field"><label>Username dell’adulto</label><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="@username" required/></div><button className="btn primary" disabled={busy}><UserPlus size={16}/> Invita adulto responsabile</button></form>{msg&&<p className="form-message">{msg}</p>}<div className="guardian-links">{links.filter(l=>l.minor_id===me&&l.status!=='revoked').map(l=>{const p=byId.get(l.guardian_id);return <div className="person-row" key={l.id}><div className="avatar">{String(p?.username||'A')[0].toUpperCase()}</div><div><b>{p?.full_name||p?.username||'Adulto'}</b><div className="muted">@{p?.username||'—'} · {l.status==='accepted'?'Responsabilità accettata':'In attesa di accettazione'}</div></div><button className="btn" style={{marginLeft:'auto'}} onClick={()=>revoke(l.id)}>Revoca</button></div>})}{!links.some(l=>l.minor_id===me&&l.status!=='revoked')&&<p className="muted">Nessun adulto responsabile collegato.</p>}</div></section>;
 const incoming=links.filter(l=>l.guardian_id===me&&l.status==='pending');const active=links.filter(l=>l.guardian_id===me&&l.status==='accepted');
 if(!incoming.length&&!active.length)return null;
 return <section className="card guardian-panel"><div className="settings-title-row"><div><div className="eyebrow">ACCOUNT COLLEGATI</div><h2>Responsabilità per minori</h2><p className="muted">Accettando un collegamento puoi consultare la collezione del minore. Qualunque annuncio o transazione Marketplace che effettui resta un’attività del tuo account e sotto la tua responsabilità.</p></div><ShieldCheck/></div>{msg&&<p className="form-message">{msg}</p>}{incoming.map(l=>{const p=byId.get(l.minor_id);return <div className="person-row" key={l.id}><div className="avatar">{String(p?.username||'M')[0].toUpperCase()}</div><div><b>{p?.full_name||p?.username||'Account minorenne'}</b><div className="muted">@{p?.username||'—'} chiede di collegarti come adulto responsabile.</div></div><div className="offer-actions" style={{marginLeft:'auto'}}><button className="btn primary" disabled={busy} onClick={()=>respond(l.id,true)}><Check size={15}/> Accetta</button><button className="btn" disabled={busy} onClick={()=>respond(l.id,false)}><X size={15}/> Rifiuta</button></div></div>})}{active.length>0&&<><h3>Collezioni collegate</h3><div className="watch-grid guardian-watch-grid">{watches.map(w=><article className="watch-card" key={w.id}>{w.cover_image_url&&<img src={w.cover_image_url} alt=""/>}<div className="watch-card-body"><div className="eyebrow">COLLEZIONE PROTETTA · @{w.minor_profile?.username||'utente'}</div><h3>{w.brand} {w.model}</h3><p className="muted">{w.reference||'Referenza non inserita'}</p><Link className="btn" href={`/watch/${w.id}`}>Consulta scheda</Link></div></article>)}</div></>}</section>;
}
