'use client';
import {compressImage} from './watchvault-v2';
import {getSession} from './supabase';

const base=(process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL)?.replace(/\/$/,'');
const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_PUBLISHABLE_KEY;
function headers(token?:string,json=true){const h:Record<string,string>={apikey:key||''};if(json)h['Content-Type']='application/json';if(token)h.Authorization=`Bearer ${token}`;return h}
async function rest(path:string,init:RequestInit={},anon=false){if(!base||!key)throw new Error('Configurazione Supabase incompleta');const s=getSession();if(!s&&!anon)throw new Error('Sessione scaduta. Accedi di nuovo.');const r=await fetch(`${base}/rest/v1/${path}`,{...init,headers:{...headers(s?.access_token),...(init.headers||{})}});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||d.details||d.hint||d.error_description||'Operazione non riuscita')}return r}
async function rpc(fn:string,body:Record<string,unknown>,anon=false){if(!base||!key)throw new Error('Configurazione Supabase incompleta');const s=getSession();if(!s&&!anon)throw new Error('Sessione scaduta. Accedi di nuovo.');const r=await fetch(`${base}/rest/v1/rpc/${fn}`,{method:'POST',headers:headers(s?.access_token),body:JSON.stringify(body)});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||d.details||'Operazione non riuscita')}return r}
const nowIso=()=>new Date().toISOString();

export async function fetchMarketplacePublic(){const r=await rest(`marketplace_listings?select=id,seller_id,watch_id,title,description,price,currency,condition,location,shipping_available,box_included,papers_included,status,created_at,updated_at,sold_at,hide_after,edited_at,view_count,profiles!marketplace_listings_seller_id_fkey(username,avatar_url),watches(cover_image_url,brand,model)&or=(status.eq.published,and(status.eq.sold,hide_after.gt.${encodeURIComponent(nowIso())}))&order=created_at.desc`,{},true);const rows:any[]=await r.json();for(const row of rows){const lr=await rest(`marketplace_listing_likes?listing_id=eq.${row.id}&select=user_id`,{},true);row.like_count=(await lr.json()).length}return rows}
export async function incrementListingView(id:string){await rpc('increment_marketplace_view',{p_listing:id},true)}
export async function fetchMyListings(){const s=getSession();if(!s)return[];const r=await rest(`marketplace_listings?seller_id=eq.${s.user.id}&select=*,watches(cover_image_url,brand,model)&order=created_at.desc`);return r.json()}
export async function updateListing(id:string,input:Record<string,unknown>){const r=await rest(`marketplace_listings?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...input,edited_at:nowIso(),updated_at:nowIso()})});return (await r.json())[0]}
export async function withdrawListing(id:string){return updateListing(id,{status:'removed',withdrawn_at:nowIso(),hide_after:null})}
export async function markListingSold(id:string){const sold=nowIso();const hide=new Date(Date.now()+24*3600*1000).toISOString();return updateListing(id,{status:'sold',sold_at:sold,hide_after:hide,withdrawn_at:null})}
export async function cancelListingSale(id:string){return updateListing(id,{status:'published',sold_at:null,hide_after:null,withdrawn_at:null})}
export async function republishListing(id:string){return updateListing(id,{status:'published',sold_at:null,hide_after:null,withdrawn_at:null})}
export async function toggleListingLike(id:string){const s=getSession();if(!s)throw new Error('Accedi per mettere Mi piace');const q=await rest(`marketplace_listing_likes?listing_id=eq.${id}&user_id=eq.${s.user.id}&select=listing_id`);const has=(await q.json()).length>0;if(has)await rest(`marketplace_listing_likes?listing_id=eq.${id}&user_id=eq.${s.user.id}`,{method:'DELETE'});else await rest('marketplace_listing_likes',{method:'POST',body:JSON.stringify({listing_id:id,user_id:s.user.id})});return !has}
export async function fetchListingComments(id:string){const r=await rest(`marketplace_comments?listing_id=eq.${id}&select=id,listing_id,author_id,body,status,created_at,profiles!marketplace_comments_author_id_fkey(username,avatar_url)&order=created_at.asc`);return r.json()}
export async function addListingComment(listingId:string,body:string){const s=getSession();if(!s)throw new Error('Accedi per commentare');const r=await rest('marketplace_comments',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({listing_id:listingId,author_id:s.user.id,body,status:'pending'})});return (await r.json())[0]}
export async function moderateListingComment(id:string,status:'approved'|'rejected'){await rest(`marketplace_comments?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status,updated_at:nowIso()})})}

export async function fetchMyOffersInbox(){const s=getSession();if(!s)return{received:[],sent:[]};const [a,b]=await Promise.all([rest(`marketplace_offers?seller_id=eq.${s.user.id}&select=*,marketplace_listings(title,price,status,watch_id),profiles!marketplace_offers_buyer_id_fkey(username,avatar_url)&order=created_at.desc`),rest(`marketplace_offers?buyer_id=eq.${s.user.id}&select=*,marketplace_listings(title,price,status,watch_id),profiles!marketplace_offers_seller_id_fkey(username,avatar_url)&order=created_at.desc`)]);return{received:await a.json(),sent:await b.json()}}
export async function respondToOffer(offer:any,action:'accept'|'counter'|'reject',counterAmount?:number,message?:string){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const responded=nowIso();let status='rejected';if(action==='accept')status='accepted';if(action==='counter')status='countered';await rest(`marketplace_offers?id=eq.${offer.id}`,{method:'PATCH',body:JSON.stringify({status,counter_amount:action==='counter'?counterAmount||null:null,response_message:message||null,responded_at:responded,updated_at:responded})});await rest('marketplace_offer_events',{method:'POST',body:JSON.stringify({offer_id:offer.id,actor_id:s.user.id,event_type:action,amount:action==='counter'?counterAmount||null:offer.amount||null,message:message||null})});if(action==='accept'){await markListingSold(offer.listing_id)}await rest('notifications',{method:'POST',body:JSON.stringify({user_id:offer.buyer_id,actor_id:s.user.id,type:`marketplace_offer_${action}`,title:action==='accept'?'Offerta accettata':action==='counter'?'Controproposta ricevuta':'Offerta rifiutata',body:message||null,link:'/messages'})}).catch(()=>{});return true}

async function uploadPostPhoto(file:File,userId:string){const s=getSession();if(!s||!base)throw new Error('Accedi di nuovo.');const compressed=await compressImage(file,1600,.76);const path=`${userId}/${crypto.randomUUID()}.webp`;const r=await fetch(`${base}/storage/v1/object/posts/${path}`,{method:'POST',headers:{apikey:key||'',Authorization:`Bearer ${s.access_token}`,'Content-Type':'image/webp','x-upsert':'false'},body:compressed});if(!r.ok)throw new Error('Upload foto post non riuscito');return path}
export async function searchPeople(q:string){const s=getSession();const term=encodeURIComponent(`%${q.replace(/[%_,()]/g,' ').trim()}%`);const r=await rest(`profiles?or=(username.ilike.${term},full_name.ilike.${term})&select=id,username,full_name,avatar_url,bio,city,country&limit=20`);const rows:any[]=await r.json();if(!s)return rows;const f=await rest(`follows?follower_id=eq.${s.user.id}&select=following_id`);const ids=new Set((await f.json()).map((x:any)=>x.following_id));return rows.filter(x=>x.id!==s.user.id).map(x=>({...x,following:ids.has(x.id)}))}
export async function toggleFollow(userId:string){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const q=await rest(`follows?follower_id=eq.${s.user.id}&following_id=eq.${userId}&select=follower_id`);const has=(await q.json()).length>0;if(has)await rest(`follows?follower_id=eq.${s.user.id}&following_id=eq.${userId}`,{method:'DELETE'});else await rest('follows',{method:'POST',body:JSON.stringify({follower_id:s.user.id,following_id:userId})});return !has}
export async function fetchCommunityPosts(){const r=await rest('posts?visibility=eq.public&select=id,author_id,body,created_at,updated_at,edited_at,profiles!posts_author_id_fkey(username,avatar_url)&order=created_at.desc&limit=50');const posts:any[]=await r.json();if(!posts.length)return[];const ids=posts.map(x=>x.id);const inFilter=`in.(${ids.join(',')})`;const [imgs,cs,ls,rs]=await Promise.all([rest(`post_images?post_id=${inFilter}&select=id,post_id,storage_path,sort_order&order=sort_order.asc`),rest(`comments?post_id=${inFilter}&select=id,post_id,author_id,body,created_at,profiles!comments_author_id_fkey(username,avatar_url)&order=created_at.asc`),rest(`likes?post_id=${inFilter}&select=post_id,user_id`),rest(`post_reactions?post_id=${inFilter}&select=post_id,user_id,sticker`)]);const images:any[]=await imgs.json(),comments:any[]=await cs.json(),likes:any[]=await ls.json(),reactions:any[]=await rs.json();return posts.map(p=>({...p,images:images.filter(x=>x.post_id===p.id),comments:comments.filter(x=>x.post_id===p.id),likes:likes.filter(x=>x.post_id===p.id),reactions:reactions.filter(x=>x.post_id===p.id)}))}
export async function createCommunityPost(body:string,files:File[]=[]){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const pr=await rest('posts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({author_id:s.user.id,body,visibility:'public'})});const post=(await pr.json())[0];const paths=[] as string[];for(const file of files.slice(0,6))paths.push(await uploadPostPhoto(file,s.user.id));if(paths.length)await rest('post_images',{method:'POST',body:JSON.stringify(paths.map((storage_path,i)=>({post_id:post.id,owner_id:s.user.id,storage_path,sort_order:i})))});return post}
export async function editCommunityPost(id:string,body:string){const t=nowIso();await rest(`posts?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({body,updated_at:t,edited_at:t})})}
export async function togglePostLike(postId:string){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const q=await rest(`likes?post_id=eq.${postId}&user_id=eq.${s.user.id}&select=post_id`);const has=(await q.json()).length>0;if(has)await rest(`likes?post_id=eq.${postId}&user_id=eq.${s.user.id}`,{method:'DELETE'});else await rest('likes',{method:'POST',body:JSON.stringify({post_id:postId,user_id:s.user.id})});return !has}
export async function addPostComment(postId:string,body:string){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');await rest('comments',{method:'POST',body:JSON.stringify({post_id:postId,author_id:s.user.id,body})})}
export async function toggleSticker(postId:string,sticker:string){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const q=await rest(`post_reactions?post_id=eq.${postId}&user_id=eq.${s.user.id}&sticker=eq.${encodeURIComponent(sticker)}&select=post_id`);const has=(await q.json()).length>0;if(has)await rest(`post_reactions?post_id=eq.${postId}&user_id=eq.${s.user.id}&sticker=eq.${encodeURIComponent(sticker)}`,{method:'DELETE'});else await rest('post_reactions',{method:'POST',body:JSON.stringify({post_id:postId,user_id:s.user.id,sticker})});return !has}
