'use client';
import {getSession} from './supabase';
const base=(process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL)?.replace(/\/$/,'');
const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_PUBLISHABLE_KEY;
function headers(token?:string){const h:Record<string,string>={apikey:key||'','Content-Type':'application/json'};if(token)h.Authorization=`Bearer ${token}`;return h}
async function rest(path:string,init:RequestInit={}){const s=getSession();if(!s||!base||!key)throw new Error('Sessione scaduta. Accedi di nuovo.');const r=await fetch(`${base}/rest/v1/${path}`,{...init,headers:{...headers(s.access_token),...(init.headers||{})}});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||d.details||'Operazione non riuscita')}return r}
export async function fetchFriendRequests(){const s=getSession();if(!s)return{incoming:[],outgoing:[],friends:[]};const [inR,outR]=await Promise.all([rest(`friend_requests?addressee_id=eq.${s.user.id}&select=*,profiles!friend_requests_requester_id_fkey(username,full_name,avatar_url)&order=created_at.desc`),rest(`friend_requests?requester_id=eq.${s.user.id}&select=*,profiles!friend_requests_addressee_id_fkey(username,full_name,avatar_url)&order=created_at.desc`)]);const incoming:any[]=await inR.json(),outgoing:any[]=await outR.json();return{incoming:incoming.filter(x=>x.status==='pending'),outgoing:outgoing.filter(x=>x.status==='pending'),friends:[...incoming.filter(x=>x.status==='accepted'),...outgoing.filter(x=>x.status==='accepted')]}}
export async function sendFriendRequest(userId:string){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const existing=await rest(`friend_requests?or=(and(requester_id.eq.${s.user.id},addressee_id.eq.${userId}),and(requester_id.eq.${userId},addressee_id.eq.${s.user.id}))&select=id,status,requester_id,addressee_id`);const rows:any[]=await existing.json();if(rows.some(x=>x.status==='accepted'))throw new Error('Siete già amici.');if(rows.some(x=>x.status==='pending'))throw new Error('C’è già una richiesta di amicizia in attesa.');if(rows[0]){await rest(`friend_requests?id=eq.${rows[0].id}`,{method:'PATCH',body:JSON.stringify({requester_id:s.user.id,addressee_id:userId,status:'pending',responded_at:null,created_at:new Date().toISOString()})});return}await rest('friend_requests',{method:'POST',body:JSON.stringify({requester_id:s.user.id,addressee_id:userId,status:'pending'})})}
export async function respondFriendRequest(id:string,status:'accepted'|'rejected'){await rest(`friend_requests?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status,responded_at:new Date().toISOString()})})}
