'use client';
import {useEffect,useState} from 'react';
export const locales=['it','en','fr','es','ru'] as const;
export type Locale=typeof locales[number];
export const localeNames:Record<Locale,string>={it:'Italiano',en:'English',fr:'Français',es:'Español',ru:'Русский'};
const KEY='watchvault-locale';
export function detectLocale():Locale{if(typeof window==='undefined')return'it';const saved=localStorage.getItem(KEY) as Locale|null;if(saved&&locales.includes(saved))return saved;const lang=(navigator.languages?.[0]||navigator.language||'it').toLowerCase().split('-')[0] as Locale;return locales.includes(lang)?lang:'en'}
export function saveLocale(locale:Locale){if(typeof window!=='undefined'){localStorage.setItem(KEY,locale);document.documentElement.lang=locale;window.dispatchEvent(new CustomEvent('watchvault-locale',{detail:locale}))}}
export function useLocale(){const[l,setL]=useState<Locale>('it');useEffect(()=>{const sync=()=>setL(detectLocale());sync();window.addEventListener('watchvault-locale',sync);return()=>window.removeEventListener('watchvault-locale',sync)},[]);return l}
const dictionaries={
it:{dashboard:'Dashboard',collection:'Collezione',passport:'Watch Passport',care:'Watch Care',knowledge:'Knowledge Base',community:'Community',marketplace:'Marketplace',myListings:'Le mie inserzioni',messages:'Messaggi e offerte',notifications:'Notifiche',search:'Ricerca',profile:'Profilo',settings:'Impostazioni',home:'Home',watches:'Orologi',add:'Aggiungi',social:'Social',more:'Altro',allFeatures:'Tutte le funzioni',login:'Accedi',register:'Registrati',welcome:'BENTORNATO',loginTitle:'Accedi a WatchVault',loginIntro:'Accedi alla tua collezione, community e marketplace.',email:'Email',password:'Password',wait:'Attendi…',forgot:'Password dimenticata?',enterEmail:'Inserisci prima la tua email.',recoverySent:'Email di recupero inviata. Controlla anche lo spam.',story:'La nostra storia',privacy:'Privacy',terms:'Termini',language:'Lingua',logout:'Esci'},
en:{dashboard:'Dashboard',collection:'Collection',passport:'Watch Passport',care:'Watch Care',knowledge:'Knowledge Base',community:'Community',marketplace:'Marketplace',myListings:'My listings',messages:'Messages & offers',notifications:'Notifications',search:'Search',profile:'Profile',settings:'Settings',home:'Home',watches:'Watches',add:'Add',social:'Social',more:'More',allFeatures:'All features',login:'Sign in',register:'Sign up',welcome:'WELCOME BACK',loginTitle:'Sign in to WatchVault',loginIntro:'Access your collection, community and marketplace.',email:'Email',password:'Password',wait:'Please wait…',forgot:'Forgot password?',enterEmail:'Enter your email first.',recoverySent:'Recovery email sent. Please also check spam.',story:'Our story',privacy:'Privacy',terms:'Terms',language:'Language',logout:'Sign out'},
fr:{dashboard:'Tableau de bord',collection:'Collection',passport:'Watch Passport',care:'Watch Care',knowledge:'Base de connaissances',community:'Communauté',marketplace:'Marketplace',myListings:'Mes annonces',messages:'Messages et offres',notifications:'Notifications',search:'Recherche',profile:'Profil',settings:'Paramètres',home:'Accueil',watches:'Montres',add:'Ajouter',social:'Social',more:'Plus',allFeatures:'Toutes les fonctions',login:'Connexion',register:"S'inscrire",welcome:'BON RETOUR',loginTitle:'Connectez-vous à WatchVault',loginIntro:'Accédez à votre collection, à la communauté et au marketplace.',email:'E-mail',password:'Mot de passe',wait:'Patientez…',forgot:'Mot de passe oublié ?',enterEmail:"Saisissez d'abord votre e-mail.",recoverySent:'E-mail de récupération envoyé. Vérifiez aussi les spams.',story:'Notre histoire',privacy:'Confidentialité',terms:'Conditions',language:'Langue',logout:'Déconnexion'},
es:{dashboard:'Panel',collection:'Colección',passport:'Watch Passport',care:'Watch Care',knowledge:'Base de conocimiento',community:'Comunidad',marketplace:'Marketplace',myListings:'Mis anuncios',messages:'Mensajes y ofertas',notifications:'Notificaciones',search:'Buscar',profile:'Perfil',settings:'Ajustes',home:'Inicio',watches:'Relojes',add:'Añadir',social:'Social',more:'Más',allFeatures:'Todas las funciones',login:'Entrar',register:'Registrarse',welcome:'BIENVENIDO DE NUEVO',loginTitle:'Entra en WatchVault',loginIntro:'Accede a tu colección, comunidad y marketplace.',email:'Correo electrónico',password:'Contraseña',wait:'Espera…',forgot:'¿Olvidaste la contraseña?',enterEmail:'Introduce primero tu correo.',recoverySent:'Correo de recuperación enviado. Revisa también el spam.',story:'Nuestra historia',privacy:'Privacidad',terms:'Términos',language:'Idioma',logout:'Salir'},
ru:{dashboard:'Панель',collection:'Коллекция',passport:'Watch Passport',care:'Watch Care',knowledge:'База знаний',community:'Сообщество',marketplace:'Маркетплейс',myListings:'Мои объявления',messages:'Сообщения и предложения',notifications:'Уведомления',search:'Поиск',profile:'Профиль',settings:'Настройки',home:'Главная',watches:'Часы',add:'Добавить',social:'Соцсеть',more:'Ещё',allFeatures:'Все функции',login:'Войти',register:'Регистрация',welcome:'С ВОЗВРАЩЕНИЕМ',loginTitle:'Войти в WatchVault',loginIntro:'Откройте свою коллекцию, сообщество и маркетплейс.',email:'Эл. почта',password:'Пароль',wait:'Подождите…',forgot:'Забыли пароль?',enterEmail:'Сначала введите электронную почту.',recoverySent:'Письмо для восстановления отправлено. Проверьте также спам.',story:'Наша история',privacy:'Конфиденциальность',terms:'Условия',language:'Язык',logout:'Выйти'}
} as const;
export function t(locale:Locale,key:keyof typeof dictionaries.it){return dictionaries[locale][key]||dictionaries.it[key]}
export const copy=dictionaries;
