'use client';
import {getSession} from './supabase';
const base=(process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL)?.replace(/\/$/,'');
const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_PUBLISHABLE_KEY;
function headers(token?:string){return {'Content-Type':'application/json',apikey:key||'',...(token?{Authorization:`Bearer ${token}`}:{})}}
async function rest(path:string,init:RequestInit={}){const s=getSession();if(!s||!base||!key)throw new Error('Sessione scaduta. Accedi di nuovo.');const r=await fetch(`${base}/rest/v1/${path}`,{...init,headers:{...headers(s.access_token),...(init.headers||{})}});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||d.details||'Operazione non riuscita')}return r}
export async function replyToComment(postId:string,parentId:string,body:string){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');await rest('comments',{method:'POST',body:JSON.stringify({post_id:postId,parent_id:parentId,author_id:s.user.id,body})})}
export async function editComment(id:string,body:string){const t=new Date().toISOString();await rest(`comments?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({body,edited_at:t,updated_at:t})})}
export async function deleteComment(id:string){const t=new Date().toISOString();await rest(`comments?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({body:'Commento eliminato',deleted_at:t,updated_at:t})})}
export async function enrichCommunityPosts(posts:any[]){if(!posts.length)return posts;const postIds=posts.map(p=>p.id);const authorIds=new Set<string>();posts.forEach(p=>authorIds.add(p.author_id));const cr=await rest(`comments?post_id=in.(${postIds.join(',')})&select=id,post_id,author_id,parent_id,body,created_at,updated_at,edited_at,deleted_at&order=created_at.asc`);const comments:any[]=await cr.json();comments.forEach(c=>authorIds.add(c.author_id));const ids=[...authorIds];let profiles:any[]=[];if(ids.length){const pr=await rest(`profiles?id=in.(${ids.join(',')})&select=id,username,full_name,avatar_url,collector_verified,seller_verified`);profiles=await pr.json()}const byId=new Map(profiles.map(p=>[p.id,p]));return posts.map(p=>({...p,profiles:byId.get(p.author_id)||p.profiles,comments:comments.filter(c=>c.post_id===p.id).map(c=>({...c,profiles:byId.get(c.author_id)}))}))}
export function publicName(profile:any){const full=String(profile?.full_name||'').trim();if(!full)return profile?.username||'Utente';const parts=full.split(/\s+/);return parts.length>1?`${parts[0]} ${parts[parts.length-1][0].toUpperCase()}.`:parts[0]}
