import type { Watch } from './types';
export const hasSupabase=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);const base=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,'');const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;const SESSION='watchvault-session';
type Session={access_token:string;user:{id:string}};
const headers=(token?:string,json=true)=>{const h:Record<string,string>={apikey:key||''};if(json)h['Content-Type']='application/json';if(token)h.Authorization=`Bearer ${token}`;return h};
export function getSession():Session|null{if(typeof window==='undefined')return null;try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch{return null}}
export async function signIn(email:string,password:string){const r=await fetch(`${base}/auth/v1/token?grant_type=password`,{method:'POST',headers:headers(),body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error(data.msg||data.error_description||'Accesso non riuscito');localStorage.setItem(SESSION,JSON.stringify(data));return data}
export async function signUp(email:string,password:string,username:string){const r=await fetch(`${base}/auth/v1/signup`,{method:'POST',headers:headers(),body:JSON.stringify({email,password,data:{username}})});const data=await r.json();if(!r.ok)throw new Error(data.msg||data.error_description||'Registrazione non riuscita');return data}
export async function uploadWatchPhoto(file:File,userId:string,token:string){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${userId}/${crypto.randomUUID()}.${ext}`;const r=await fetch(`${base}/storage/v1/object/watch-photos/${path}`,{method:'POST',headers:{...headers(token,false),'Content-Type':file.type||'image/jpeg','x-upsert':'false'},body:file});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||'Caricamento foto non riuscito')}return `${base}/storage/v1/object/public/watch-photos/${path}`}
export async function fetchMyWatches():Promise<Watch[]>{const s=getSession();if(!hasSupabase||!s)return[];const r=await fetch(`${base}/rest/v1/watches?owner_id=eq.${s.user.id}&select=*&order=created_at.desc`,{headers:headers(s.access_token)});if(!r.ok)throw new Error('Impossibile caricare la collezione');const rows=await r.json();return rows.map((x:any)=>({id:x.id,brand:x.brand,model:x.model,reference:x.reference||'',year:x.production_year?.toString()||'',movement:x.movement||'',caliber:x.caliber||'',diameter:x.diameter||'',material:x.material||'',dial:x.dial||'',waterResistance:x.water_resistance||'',purchasePrice:Number(x.purchase_price||0),currentValue:Number(x.current_value||0),condition:x.condition||'',status:x.status||'In collezione',image:x.cover_image_url||'',serial:x.serial_encrypted||'',notes:x.notes||''}))}
export async function createWatch(w:Watch,file?:File|null){const s=getSession();if(!hasSupabase||!s)throw new Error('Accedi per salvare online');const image=file?await uploadWatchPhoto(file,s.user.id,s.access_token):w.image;const payload={owner_id:s.user.id,brand:w.brand,model:w.model,reference:w.reference||null,production_year:w.year?Number(w.year):null,purchase_price:w.purchasePrice||0,current_value:w.currentValue||0,condition:w.condition,status:w.status,notes:w.notes||null,movement:w.movement||null,caliber:w.caliber||null,cover_image_url:image||null};const r=await fetch(`${base}/rest/v1/watches`,{method:'POST',headers:{...headers(s.access_token),Prefer:'return=representation'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.message||'Salvataggio non riuscito');return{...w,id:data[0].id,image}}
