import type { Watch } from './types';

export const hasSupabase=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL&&process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY);
const base=process.env.NEXT_PUBLIC_SUPABASE_URL?.replace(/\/$/,'');
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
const SESSION='watchvault-session';
export type Session={access_token:string;refresh_token?:string;expires_at?:number;user:{id:string;email?:string;user_metadata?:{username?:string}}};
const headers=(token?:string,json=true)=>{const h:Record<string,string>={apikey:key||''};if(json)h['Content-Type']='application/json';if(token)h.Authorization=`Bearer ${token}`;return h};
function requireConfig(){if(!hasSupabase||!base||!key)throw new Error('WatchVault non è ancora collegato a Supabase. Configura le variabili su Render.')}
export function getSession():Session|null{if(typeof window==='undefined')return null;try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch{return null}}
export function clearSession(){if(typeof window!=='undefined')localStorage.removeItem(SESSION)}
export function isLoggedIn(){return Boolean(getSession()?.access_token)}
export async function signIn(email:string,password:string){requireConfig();const r=await fetch(`${base}/auth/v1/token?grant_type=password`,{method:'POST',headers:headers(),body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error(data.msg||data.error_description||data.error||'Accesso non riuscito');localStorage.setItem(SESSION,JSON.stringify(data));return data as Session}
export async function signUp(email:string,password:string,username:string){requireConfig();const redirectTo=typeof window!=='undefined'?`${window.location.origin}/login`:undefined;const r=await fetch(`${base}/auth/v1/signup`,{method:'POST',headers:headers(),body:JSON.stringify({email,password,data:{username},email_redirect_to:redirectTo})});const data=await r.json();if(!r.ok)throw new Error(data.msg||data.error_description||data.error||'Registrazione non riuscita');if(data.access_token)localStorage.setItem(SESSION,JSON.stringify(data));return data}
export async function signOut(){const s=getSession();if(s?.access_token&&base)await fetch(`${base}/auth/v1/logout`,{method:'POST',headers:headers(s.access_token)}).catch(()=>{});clearSession()}
async function rest(path:string,init:RequestInit={}){requireConfig();const s=getSession();if(!s)throw new Error('Sessione scaduta. Accedi di nuovo.');const r=await fetch(`${base}/rest/v1/${path}`,{...init,headers:{...headers(s.access_token),...(init.headers||{})}});if(r.status===401){clearSession();throw new Error('Sessione scaduta. Accedi di nuovo.')}if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||d.details||d.hint||'Operazione non riuscita')}return r}
export async function uploadWatchPhoto(file:File,userId:string,token:string){requireConfig();const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${userId}/${crypto.randomUUID()}.${ext}`;const r=await fetch(`${base}/storage/v1/object/watch-photos/${path}`,{method:'POST',headers:{...headers(token,false),'Content-Type':file.type||'image/jpeg','x-upsert':'false'},body:file});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||'Caricamento foto non riuscito')}return `${base}/storage/v1/object/public/watch-photos/${path}`}
const mapWatch=(x:any):Watch=>({id:x.id,brand:x.brand,model:x.model,reference:x.reference||'',year:x.production_year?.toString()||'',movement:x.movement||'',caliber:x.caliber||'',diameter:x.diameter_mm?.toString()||'',material:x.material||'',dial:x.dial||'',waterResistance:x.water_resistance_m?.toString()||'',purchasePrice:Number(x.purchase_price||0),currentValue:Number(x.current_value||0),condition:x.condition||'',status:x.status||'In collezione',image:x.cover_image_url||'',serial:x.serial_encrypted||'',notes:x.notes||''});
export async function fetchMyWatches():Promise<Watch[]>{const s=getSession();if(!s)return[];const r=await rest(`watches?owner_id=eq.${s.user.id}&select=*&order=created_at.desc`);return(await r.json()).map(mapWatch)}
export async function createWatch(w:Watch,file?:File|null){const s=getSession();if(!s)throw new Error('Accedi per salvare online');const image=file?await uploadWatchPhoto(file,s.user.id,s.access_token):w.image;const payload={owner_id:s.user.id,brand:w.brand,model:w.model,reference:w.reference||null,production_year:w.year?Number(w.year):null,purchase_price:w.purchasePrice||0,current_value:w.currentValue||0,condition:w.condition,status:w.status,notes:w.notes||null,movement:w.movement||null,caliber:w.caliber||null,diameter_mm:w.diameter?Number(w.diameter):null,material:w.material||null,dial:w.dial||null,water_resistance_m:w.waterResistance?Number(w.waterResistance):null,cover_image_url:image||null};const r=await rest('watches',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});const data=await r.json();return mapWatch(data[0])}
export async function deleteWatch(id:string){await rest(`watches?id=eq.${id}`,{method:'DELETE'});}
export type MaintenanceRow={id:string;watch_id:string;watch_name:string;type:string;performed_at:string|null;due_at:string|null;provider:string|null;cost:number;notes:string|null;status:string};
export async function fetchMaintenance():Promise<MaintenanceRow[]>{const s=getSession();if(!s)return[];const r=await rest(`maintenance?owner_id=eq.${s.user.id}&select=id,watch_id,type,performed_at,due_at,provider,cost,notes,status,watches(brand,model)&order=due_at.asc.nullslast`);const rows=await r.json();return rows.map((x:any)=>({...x,watch_name:x.watches?`${x.watches.brand} ${x.watches.model}`:'Orologio',cost:Number(x.cost||0)}))}
export async function createMaintenance(input:{watch_id:string;type:string;performed_at?:string;due_at?:string;provider?:string;cost?:number;notes?:string;status?:string}){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const payload={owner_id:s.user.id,watch_id:input.watch_id,type:input.type,performed_at:input.performed_at||null,due_at:input.due_at||null,provider:input.provider||null,cost:input.cost||0,notes:input.notes||null,status:input.status||'planned'};const r=await rest('maintenance',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});return(await r.json())[0]}
export type PostRow={id:string;body:string;image_url:string|null;created_at:string;author_id:string;profiles?:{username:string;avatar_url:string|null}|null};
export async function fetchPosts():Promise<PostRow[]>{const r=await rest('posts?select=id,body,image_url,created_at,author_id,profiles(username,avatar_url)&order=created_at.desc&limit=50');return r.json()}
export async function createPost(body:string){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const r=await rest('posts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({author_id:s.user.id,body})});return(await r.json())[0]}
export type ListingRow={id:string;title:string;description:string|null;price:number;condition:string|null;location:string|null;status:string;created_at:string;profiles?:{username:string}|null;watches?:{cover_image_url:string|null}|null};
export async function fetchListings():Promise<ListingRow[]>{const r=await rest('listings?status=eq.active&select=id,title,description,price,condition,location,status,created_at,profiles(username),watches(cover_image_url)&order=created_at.desc');const rows=await r.json();return rows.map((x:any)=>({...x,price:Number(x.price||0)}))}
export async function createListing(input:{watch_id?:string;title:string;description?:string;price:number;condition?:string;location?:string}){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const r=await rest('listings',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({...input,watch_id:input.watch_id||null,seller_id:s.user.id,status:'active'})});return(await r.json())[0]}
export type ProfileRow={id:string;username:string;full_name:string|null;avatar_url:string|null;bio:string|null;country:string|null;city:string|null;privacy:string;created_at:string};
export async function fetchMyProfile():Promise<ProfileRow>{const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const r=await rest(`profiles?id=eq.${s.user.id}&select=*&limit=1`);const rows=await r.json();if(!rows[0])throw new Error('Profilo non trovato');return rows[0]}
export async function updateMyProfile(input:Partial<Pick<ProfileRow,'username'|'full_name'|'bio'|'country'|'city'|'privacy'>>){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const r=await rest(`profiles?id=eq.${s.user.id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(input)});return(await r.json())[0] as ProfileRow}
