import type { Watch } from './types';

const base=(process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL)?.replace(/\/$/,'');
const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_PUBLISHABLE_KEY;
export const hasSupabase=Boolean(base&&key);
const SESSION='watchvault-session-v2';
export type Session={access_token:string;refresh_token?:string;expires_at?:number;user:{id:string;email?:string;user_metadata?:Record<string,any>}};
const headers=(token?:string,json=true)=>{const h:Record<string,string>={apikey:key||''};if(json)h['Content-Type']='application/json';if(token)h.Authorization=`Bearer ${token}`;return h};
function requireConfig(){if(!hasSupabase||!base||!key)throw new Error('WatchVault non è collegato a Supabase. Configura URL e publishable key su Render.')}
export function getSession():Session|null{if(typeof window==='undefined')return null;try{return JSON.parse(localStorage.getItem(SESSION)||'null')}catch{return null}}
export function clearSession(){if(typeof window!=='undefined')localStorage.removeItem(SESSION)}
export function isLoggedIn(){return Boolean(getSession()?.access_token)}
export async function signIn(email:string,password:string){requireConfig();const r=await fetch(`${base}/auth/v1/token?grant_type=password`,{method:'POST',headers:headers(),body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error(data.msg||data.error_description||data.error||'Accesso non riuscito');localStorage.setItem(SESSION,JSON.stringify(data));return data as Session}
export async function signUp(email:string,password:string,username:string,legal?:{termsVersion:string;privacyVersion:string;marketingConsent:boolean;birthDate?:string;gender?:string;minorAccount?:boolean}){requireConfig();const redirectTo=typeof window!=='undefined'?`${window.location.origin}/login`:undefined;const locale=typeof window!=='undefined'?(localStorage.getItem('watchvault-locale')||navigator.language?.split('-')[0]||'it'):'it';const acceptedAt=new Date().toISOString();const r=await fetch(`${base}/auth/v1/signup`,{method:'POST',headers:headers(),body:JSON.stringify({email,password,data:{username,locale,birth_date:legal?.birthDate||null,gender:legal?.gender||'prefer_not_say',minor_account:Boolean(legal?.minorAccount),account_tier:legal?.minorAccount?'minor_basic':'standard',terms_version:legal?.termsVersion||null,privacy_version:legal?.privacyVersion||null,legal_accepted_at:legal?acceptedAt:null,marketing_consent:legal?.minorAccount?false:Boolean(legal?.marketingConsent),marketing_consent_at:legal?.marketingConsent&&!legal?.minorAccount?acceptedAt:null},email_redirect_to:redirectTo})});const data=await r.json();if(!r.ok)throw new Error(data.msg||data.error_description||data.error||'Registrazione non riuscita');if(data.access_token)localStorage.setItem(SESSION,JSON.stringify(data));return data}
export async function requestPasswordReset(email:string){requireConfig();const redirectTo=typeof window!=='undefined'?`${window.location.origin}/login?reset=1`:undefined;const r=await fetch(`${base}/auth/v1/recover`,{method:'POST',headers:headers(),body:JSON.stringify({email,redirect_to:redirectTo})});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.msg||d.error_description||'Impossibile inviare il recupero password')}return true}
export async function signOut(){const s=getSession();if(s?.access_token&&base)await fetch(`${base}/auth/v1/logout`,{method:'POST',headers:headers(s.access_token)}).catch(()=>{});clearSession()}
async function rest(path:string,init:RequestInit={},allowAnon=false){requireConfig();const s=getSession();if(!s&&!allowAnon)throw new Error('Sessione scaduta. Accedi di nuovo.');const r=await fetch(`${base}/rest/v1/${path}`,{...init,headers:{...headers(s?.access_token),...(init.headers||{})}});if(r.status===401&&s){clearSession();throw new Error('Sessione scaduta. Accedi di nuovo.')}if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||d.details||d.hint||'Operazione non riuscita')}return r}
async function upload(bucket:string,file:File,userId:string,token:string){requireConfig();const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${userId}/${crypto.randomUUID()}-${safe}`;const r=await fetch(`${base}/storage/v1/object/${bucket}/${path}`,{method:'POST',headers:{...headers(token,false),'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.message||'Upload non riuscito')}return {path,url:bucket==='documents'?null:`${base}/storage/v1/object/public/${bucket}/${path}`}}
export async function uploadWatchPhoto(file:File,userId:string,token:string){return (await upload('watches',file,userId,token)).url||''}
export async function uploadAvatar(file:File){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');return upload('avatars',file,s.user.id,s.access_token)}

const mapWatch=(x:any):Watch=>({id:x.id,brand:x.brand,model:x.model,reference:x.reference||'',year:x.production_year?.toString()||'',movement:x.movement||x.movement_type||'',caliber:x.caliber||'',diameter:x.diameter_mm?.toString()||'',material:x.material||'',dial:x.dial_color||'',waterResistance:x.water_resistance_m?.toString()||'',purchasePrice:Number(x.purchase_price||0),currentValue:Number(x.estimated_value||0),condition:x.condition||'',status:x.status||'collection',image:x.cover_image_url||'',serial:x.serial_number||'',notes:x.private_notes||''});
export async function fetchMyWatches():Promise<Watch[]>{const s=getSession();if(!s)return[];const r=await rest(`watches?owner_id=eq.${s.user.id}&select=*&order=created_at.desc`);return(await r.json()).map(mapWatch)}
export async function createWatch(w:Watch,file?:File|null){const s=getSession();if(!s)throw new Error('Accedi per salvare online');const image=file?await uploadWatchPhoto(file,s.user.id,s.access_token):w.image;const payload={owner_id:s.user.id,brand:w.brand,model:w.model,reference:w.reference||null,production_year:w.year?Number(w.year):null,purchase_price:w.purchasePrice||0,estimated_value:w.currentValue||0,condition:w.condition||null,status:w.status||'collection',private_notes:w.notes||null,movement:w.movement||null,caliber:w.caliber||null,diameter_mm:w.diameter?Number(w.diameter):null,material:w.material||null,dial_color:w.dial||null,water_resistance_m:w.waterResistance?Number(w.waterResistance):null,cover_image_url:image||null,serial_number:w.serial||null,visibility:'private'};const r=await rest('watches',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});const data=await r.json();return mapWatch(data[0])}
export async function updateWatch(id:string,input:Record<string,unknown>){const r=await rest(`watches?id=eq.${id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(input)});return mapWatch((await r.json())[0])}
export async function deleteWatch(id:string){await rest(`watches?id=eq.${id}`,{method:'DELETE'});}

export type MaintenanceRow={id:string;watch_id:string;watch_name:string;type:string;performed_at:string|null;due_at:string|null;provider:string|null;cost:number;notes:string|null;status:string};
const serviceType=(label:string)=>{const x=label.toLowerCase();if(x.includes('batter'))return'batteria';if(x.includes('solare'))return'ricarica_solare';if(x.includes('imperme'))return'impermeabilita';if(x.includes('lucid'))return'lucidatura';if(x.includes('vetro'))return'vetro';if(x.includes('cintur'))return'cinturino';if(x.includes('guarn'))return'guarnizioni';if(x.includes('precision')||x.includes('regolazione'))return'precisione';if(x.includes('movimento')||x.includes('restauro'))return'movimento';if(x.includes('tagliando'))return'tagliando';return'altro'};
export async function fetchMaintenance():Promise<MaintenanceRow[]>{const s=getSession();if(!s)return[];const r=await rest(`watch_service_history?owner_id=eq.${s.user.id}&select=id,watch_id,service_type,service_date,next_due_date,provider,cost,notes,watches(brand,model)&order=next_due_date.asc.nullslast`);const rows=await r.json();return rows.map((x:any)=>({id:x.id,watch_id:x.watch_id,watch_name:x.watches?`${x.watches.brand} ${x.watches.model}`:'Orologio',type:x.service_type,performed_at:x.service_date,due_at:x.next_due_date,provider:x.provider,cost:Number(x.cost||0),notes:x.notes,status:x.next_due_date?'planned':'done'}))}
export async function createMaintenance(input:{watch_id:string;type:string;performed_at?:string;due_at?:string;provider?:string;cost?:number;notes?:string;status?:string}){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const payload={owner_id:s.user.id,watch_id:input.watch_id,service_type:serviceType(input.type),service_date:input.performed_at||new Date().toISOString().slice(0,10),next_due_date:input.due_at||null,provider:input.provider||null,cost:input.cost||0,notes:input.notes||null};const r=await rest('watch_service_history',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)});return(await r.json())[0]}

export type PostRow={id:string;body:string;created_at:string;author_id:string;image_url?:string|null;profiles?:{username:string;avatar_url:string|null}|null};
export async function fetchPosts():Promise<PostRow[]>{const r=await rest('posts?visibility=eq.public&select=id,body,created_at,author_id,profiles!posts_author_id_fkey(username,avatar_url)&order=created_at.desc&limit=50',{},true);return r.json()}
export async function createPost(body:string){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const r=await rest('posts',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({author_id:s.user.id,body,visibility:'public'})});return(await r.json())[0]}

export type ListingRow={id:string;title:string;description:string|null;price:number;condition:string|null;location:string|null;status:string;created_at:string;profiles?:{username:string}|null;watches?:{cover_image_url:string|null}|null};
export async function fetchListings():Promise<ListingRow[]>{const r=await rest('marketplace_listings?status=eq.published&select=id,title,description,price,condition,location,status,created_at,profiles(username),watches(cover_image_url)&order=created_at.desc',{},true);const rows=await r.json();return rows.map((x:any)=>({...x,price:Number(x.price||0)}))}
export async function createListing(input:{watch_id?:string;title:string;description?:string;price:number;condition?:string;location?:string}){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const r=await rest('marketplace_listings',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({...input,watch_id:input.watch_id||null,seller_id:s.user.id,status:'published'})});return(await r.json())[0]}

export type ProfileRow={id:string;username:string;full_name:string|null;avatar_url:string|null;bio:string|null;country:string|null;city:string|null;profile_visibility:string;role:string;status:string;created_at:string};
export async function fetchMyProfile():Promise<ProfileRow>{const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const r=await rest(`profiles?id=eq.${s.user.id}&select=*&limit=1`);const rows=await r.json();if(!rows[0])throw new Error('Profilo non trovato');return rows[0]}
export async function updateMyProfile(input:Partial<Pick<ProfileRow,'username'|'full_name'|'bio'|'country'|'city'|'profile_visibility'|'avatar_url'>>){const s=getSession();if(!s)throw new Error('Accedi di nuovo.');const r=await rest(`profiles?id=eq.${s.user.id}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(input)});return(await r.json())[0] as ProfileRow}

export async function globalSearch(q:string){const clean=q.replace(/[%_,()]/g,' ').trim();const term=encodeURIComponent(`%${clean}%`);const [users,brands,models,watches,posts,listings]=await Promise.all([rest(`profiles?or=(username.ilike.${term},full_name.ilike.${term})&select=id,username,avatar_url&limit=8`,{},true).then(r=>r.json()),rest(`brands?name=ilike.${term}&select=id,name,slug&limit=8`,{},true).then(r=>r.json()),rest(`watch_models?model=ilike.${term}&select=id,model,reference&limit=8`,{},true).then(r=>r.json()),rest(`watches?visibility=eq.public&or=(brand.ilike.${term},model.ilike.${term},reference.ilike.${term})&select=id,brand,model,reference,cover_image_url&limit=8`,{},true).then(r=>r.json()),rest(`posts?visibility=eq.public&body=ilike.${term}&select=id,body,created_at&limit=8`,{},true).then(r=>r.json()),rest(`marketplace_listings?status=eq.published&or=(title.ilike.${term},description.ilike.${term})&select=id,title,price,currency&limit=8`,{},true).then(r=>r.json())]);return {users,brands,models,watches,posts,listings}}
