'use client';

export type OcrCatalogMatch={id:string;brand:string;model:string;reference?:string|null;caliber?:string|null;movement?:string|null;movement_type?:string|null;year_from?:number|null;year_to?:number|null;material?:string|null;diameter_mm?:number|null;water_resistance_m?:number|null;dial_color?:string|null;score:number};
export type WatchOcrResult={text:string;brand?:string;reference?:string;matches:OcrCatalogMatch[];confidence:number};

const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();
const tokens=(s:string)=>norm(s).split(/\s+/).filter(x=>x.length>1);
const refCandidates=(text:string)=>Array.from(new Set((text.toUpperCase().match(/\b[A-Z0-9][A-Z0-9.\/-]{2,18}\b/g)||[]).filter(x=>/\d/.test(x)&&!/^\d{1,4}$/.test(x))));

async function catalog(){const url=(process.env.NEXT_PUBLIC_SUPABASE_URL||process.env.SUPABASE_URL)?.replace(/\/$/,'');const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_PUBLISHABLE_KEY;if(!url||!key)throw new Error('Catalogo WatchVault non configurato.');const h={apikey:key};const [br,mr]=await Promise.all([fetch(`${url}/rest/v1/brands?select=id,name&order=name.asc`,{headers:h}),fetch(`${url}/rest/v1/watch_models?catalog_status=eq.published&select=id,model,reference,caliber,movement,movement_type,year_from,year_to,material,diameter_mm,water_resistance_m,dial_color,brands(name)&limit=2000`,{headers:h})]);if(!br.ok||!mr.ok)throw new Error('Impossibile consultare il catalogo WatchVault.');return {brands:await br.json(),models:await mr.json()}}

function scoreModel(text:string,row:any,brand?:string,refs:string[]=[]){const hay=` ${norm(text)} `;let score=0;const b=String(row.brands?.name||'');if(brand&&norm(b)===norm(brand))score+=45;else if(b&&hay.includes(` ${norm(b)} `))score+=35;const modelTokens=tokens(row.model||'');const hit=modelTokens.filter(t=>hay.includes(` ${t} `)).length;if(modelTokens.length)score+=Math.round(30*hit/modelTokens.length);const ref=norm(row.reference||'');if(ref){if(norm(text).includes(ref))score+=55;else if(refs.some(r=>norm(r)===ref))score+=55;else if(refs.some(r=>norm(r).includes(ref)||ref.includes(norm(r))))score+=25}const cal=norm(row.caliber||'');if(cal&&norm(text).includes(cal))score+=15;return score}

export async function recognizeWatchLocally(files:File[],onProgress?:(label:string)=>void):Promise<WatchOcrResult>{if(!files.length)throw new Error('Aggiungi almeno una fotografia.');onProgress?.('Carico il motore OCR gratuito…');const {createWorker}=await import('tesseract.js');const worker=await createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text')onProgress?.(`Leggo le scritte… ${Math.round((m.progress||0)*100)}%`)}});let text='';try{for(let i=0;i<Math.min(files.length,3);i++){onProgress?.(`Analizzo foto ${i+1}/${Math.min(files.length,3)}…`);const r=await worker.recognize(files[i]);text+=`\n${r.data.text||''}`}}finally{await worker.terminate()}if(!text.trim())throw new Error('Non riesco a leggere scritte dalle foto. Prova con quadrante o fondello più nitidi e senza riflessi.');onProgress?.('Confronto con il catalogo WatchVault…');const c=await catalog();const nt=norm(text);const brandHits=c.brands.map((b:any)=>({name:b.name,n:norm(b.name)})).filter((b:any)=>b.n&&nt.includes(b.n)).sort((a:any,b:any)=>b.n.length-a.n.length);const brand=brandHits[0]?.name;const refs=refCandidates(text);const ranked=c.models.map((m:any)=>({...m,brand:m.brands?.name||'',score:scoreModel(text,m,brand,refs)})).filter((m:any)=>m.score>=25).sort((a:any,b:any)=>b.score-a.score).slice(0,3);const top=ranked[0]?.score||0;return{text:text.trim(),brand,reference:refs[0],matches:ranked,confidence:Math.min(98,Math.max(20,top))}}
