'use client';
import Nav from '@/components/Nav';
import LanguageSelector from '@/components/LanguageSelector';
import Link from 'next/link';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {signUp,hasSupabase} from '@/lib/supabase';
import {t,useLocale} from '@/lib/i18n';
export default function Register(){const locale=useLocale();const r=useRouter();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[username,setUsername]=useState('');const[terms,setTerms]=useState(false);const[marketing,setMarketing]=useState(false);const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setMsg('');if(!terms){setMsg(t(locale,'termsRequired'));return}if(!hasSupabase){setMsg('WatchVault / Supabase configuration missing.');return}setBusy(true);try{const data=await signUp(email,password,username,{termsVersion:'2026-08-08-dev-1',privacyVersion:'2026-08-08-dev-1',marketingConsent:marketing});if(data.access_token)r.replace('/dashboard');else setMsg(t(locale,'registrationDone'))}catch(err){setMsg(err instanceof Error?err.message:'Registration failed')}finally{setBusy(false)}}return <><Nav/><form className="form-wrap" onSubmit={submit}><div className="register-top"><div><div className="eyebrow">{t(locale,'joinCommunity')}</div><h1>{t(locale,'createAccount')}</h1></div><LanguageSelector/></div><div className="field"><label>{t(locale,'publicNickname')}</label><input value={username} onChange={e=>setUsername(e.target.value)} minLength={3} required/></div><div className="field"><label>{t(locale,'email')}</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="email" required/></div><div className="field"><label>{t(locale,'password')}</label><input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="new-password" minLength={8} required/></div><label className="consent-row"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)} required/><span>{t(locale,'acceptTermsPrefix')} <Link href="/terms" target="_blank">{t(locale,'termsConditions')}</Link> {t(locale,'privacyConfirm')}</span></label><label className="consent-row optional"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)}/><span>{t(locale,'marketingConsent')}</span></label>{msg&&<p className="form-message">{msg}</p>}<button className="btn primary" style={{width:'100%'}} disabled={busy}>{busy?t(locale,'creatingAccount'):t(locale,'register')}</button><p className="legal-mini">{t(locale,'legalMini')}</p></form></>}
