'use client';
import AppShell from '@/components/AppShell';
import {useEffect,useState} from 'react';
import {Check,MonitorCog,Moon,Sun,Palette,KeyRound} from 'lucide-react';
import {changePassword} from '@/lib/watchvault-v2';

type Theme='dark'|'white-luxury'|'colour-eink';
const themes:{id:Theme;name:string;description:string;icon:typeof Moon;swatches:string[]}[]=[
  {id:'dark',name:'Scuro',description:'Nero profondo, grafite e dettagli oro. Il look classico di WatchVault.',icon:Moon,swatches:['#090b10','#171c26','#d8ad5b','#f7f8fa']},
  {id:'white-luxury',name:'White Luxury',description:'Avorio, bianco caldo, champagne e nero. Elegante come una boutique di alta orologeria.',icon:Sun,swatches:['#f7f3ea','#ffffff','#b68a3d','#191713']},
  {id:'colour-eink',name:'Colour e‑Ink',description:'Carta calda, colori desaturati e contrasto morbido ispirato ai display e‑ink a colori.',icon:Palette,swatches:['#e9e3d7','#d8d4c6','#8d4f42','#3f6f68']}
];
function applyTheme(t:Theme){document.documentElement.dataset.theme=t;document.documentElement.style.colorScheme=t==='dark'?'dark':'light';localStorage.setItem('watchvault-theme',t)}
export default function SettingsPage(){const[theme,setTheme]=useState<Theme>('dark');const[p1,setP1]=useState('');const[p2,setP2]=useState('');const[msg,setMsg]=useState('');const[busy,setBusy]=useState(false);useEffect(()=>{const saved=(localStorage.getItem('watchvault-theme')||'dark') as Theme;setTheme(saved);applyTheme(saved)},[]);function choose(t:Theme){setTheme(t);applyTheme(t)}async function password(e:React.FormEvent){e.preventDefault();setMsg('');if(p1.length<8)return setMsg('La password deve avere almeno 8 caratteri.');if(p1!==p2)return setMsg('Le due password non coincidono.');setBusy(true);try{await changePassword(p1);setP1('');setP2('');setMsg('Password aggiornata correttamente.')}catch(e){setMsg(e instanceof Error?e.message:'Cambio password non riuscito')}finally{setBusy(false)}}return <AppShell><div className="pagehead settings-head"><div><div className="eyebrow">PERSONALIZZA WATCHVAULT</div><h1>Impostazioni</h1><p className="page-subtitle muted">Aspetto, sicurezza e preferenze del tuo account.</p></div><MonitorCog size={34}/></div><section className="settings-section"><h2>Aspetto</h2><p className="muted">Il tema viene salvato su questo dispositivo e applicato immediatamente.</p><div className="theme-grid">{themes.map(t=>{const Icon=t.icon;const active=theme===t.id;return <button type="button" key={t.id} className={`theme-card ${active?'selected':''}`} onClick={()=>choose(t.id)} aria-pressed={active}><div className="theme-card-top"><div className="theme-icon"><Icon size={22}/></div>{active&&<span className="theme-check"><Check size={17}/></span>}</div><div className="theme-preview" data-preview={t.id}><div className="preview-header"><span></span><span></span></div><div className="preview-hero"></div><div className="preview-row"><span></span><span></span></div></div><div className="theme-copy"><h3>{t.name}</h3><p>{t.description}</p><div className="theme-swatches">{t.swatches.map(c=><span key={c} style={{background:c}}/>)}</div></div></button>})}</div></section><section className="settings-section"><div className="settings-title-row"><div><h2>Sicurezza account</h2><p className="muted">Cambia la password senza uscire da WatchVault.</p></div><KeyRound/></div><form className="card settings-password" onSubmit={password}><div className="form-grid"><div className="field"><label>Nuova password</label><input type="password" autoComplete="new-password" minLength={8} value={p1} onChange={e=>setP1(e.target.value)} required/></div><div className="field"><label>Ripeti nuova password</label><input type="password" autoComplete="new-password" minLength={8} value={p2} onChange={e=>setP2(e.target.value)} required/></div></div>{msg&&<p className="form-message">{msg}</p>}<button className="btn primary" disabled={busy}>{busy?'Aggiornamento…':'Cambia password'}</button></form></section></AppShell>}
