import {NextRequest,NextResponse} from 'next/server';

export const runtime='nodejs';

const SYSTEM=`You are WatchVault AI, an expert watch cataloguing assistant. Analyse the supplied watch photographs, including dial, case, caseback, clasp and visible inscriptions. Return ONLY valid JSON. Never invent a serial number or exact reference if it is not legible or reliably identifiable. Use null when uncertain. Distinguish visual evidence from inference. Output: {brand,model,reference,serial,year,movement,caliber,diameter,material,dial,waterResistance,isNumbered,editionNumber,editionTotal,confidence,notes,warnings}. confidence is 0-100. year may be a year or approximate range string. waterResistance is metres when visible/reliably known. notes should briefly explain identifying evidence. warnings must remind the user to verify uncertain fields.`;

function extractText(data:any){if(typeof data?.output_text==='string')return data.output_text;for(const item of data?.output||[])for(const c of item?.content||[])if(c?.type==='output_text'&&c?.text)return c.text;return ''}

export async function POST(req:NextRequest){try{const key=process.env.OPENAI_API_KEY;if(!key)return NextResponse.json({error:'WatchVault AI non configurata sul server.'},{status:503});const body=await req.json();const images=Array.isArray(body?.images)?body.images.slice(0,4):[];if(!images.length)return NextResponse.json({error:'Aggiungi almeno una fotografia.'},{status:400});if(images.some((x:any)=>typeof x!=='string'||!x.startsWith('data:image/')))return NextResponse.json({error:'Formato immagine non valido.'},{status:400});const content:any[]=[{type:'input_text',text:'Identify this watch. Be conservative: propose fields only when visible or strongly supported. The user will review every field before saving.'},...images.map((image_url:string)=>({type:'input_image',image_url,detail:'high'}))];const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.4-mini',instructions:SYSTEM,input:[{role:'user',content}],text:{format:{type:'json_object'}},max_output_tokens:1200})});const data=await r.json();if(!r.ok)return NextResponse.json({error:data?.error?.message||'Servizio AI non disponibile.'},{status:r.status});const raw=extractText(data);let result:any;try{result=JSON.parse(raw)}catch{return NextResponse.json({error:'Risposta AI non interpretabile.'},{status:502})}return NextResponse.json({result});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Errore WatchVault AI'},{status:500})}}
