import {NextRequest,NextResponse} from 'next/server';

export const runtime='nodejs';

const SYSTEM=`You are WatchVault AI, an expert watch cataloguing assistant. Analyse the supplied watch photographs, including dial, case, caseback, clasp and visible inscriptions. Be conservative. Never invent a serial number or exact reference if it is not legible or reliably identifiable. Use null when uncertain. Distinguish visual evidence from inference. The user will verify every field before saving.`;

const schema={type:'object',additionalProperties:false,properties:{brand:{type:['string','null']},model:{type:['string','null']},reference:{type:['string','null']},serial:{type:['string','null']},year:{type:['string','number','null']},movement:{type:['string','null']},caliber:{type:['string','null']},diameter:{type:['number','null']},material:{type:['string','null']},dial:{type:['string','null']},waterResistance:{type:['number','null']},isNumbered:{type:['boolean','null']},editionNumber:{type:['number','null']},editionTotal:{type:['number','null']},confidence:{type:'number',minimum:0,maximum:100},notes:{type:'string'},warnings:{type:'array',items:{type:'string'}}},required:['brand','model','reference','serial','year','movement','caliber','diameter','material','dial','waterResistance','isNumbered','editionNumber','editionTotal','confidence','notes','warnings']};

function extractText(data:any){if(typeof data?.output_text==='string'&&data.output_text)return data.output_text;for(const item of data?.output||[])for(const c of item?.content||[])if(c?.type==='output_text'&&c?.text)return c.text;return ''}

export async function POST(req:NextRequest){try{const key=process.env.OPENAI_API_KEY;if(!key)return NextResponse.json({error:'WatchVault AI non configurata sul server.'},{status:503});const body=await req.json();const images=Array.isArray(body?.images)?body.images.slice(0,4):[];if(!images.length)return NextResponse.json({error:'Aggiungi almeno una fotografia.'},{status:400});if(images.some((x:any)=>typeof x!=='string'||!x.startsWith('data:image/')))return NextResponse.json({error:'Formato immagine non valido.'},{status:400});const totalSize=images.reduce((n:number,x:string)=>n+x.length,0);if(totalSize>18_000_000)return NextResponse.json({error:'Le foto sono troppo grandi per l’analisi. Prova con 1-2 immagini oppure riduci la dimensione.'},{status:413});const content:any[]=[{type:'input_text',text:'Identify this watch from the photos. Prefer visible evidence. Return the requested structured fields only.'},...images.map((image_url:string)=>({type:'input_image',image_url,detail:'high'}))];const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),45000);let r:Response;try{r=await fetch('https://api.openai.com/v1/responses',{method:'POST',signal:controller.signal,headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5-mini',instructions:SYSTEM,input:[{role:'user',content}],reasoning:{effort:'low'},text:{format:{type:'json_schema',name:'watch_identification',strict:true,schema}},max_output_tokens:1400})})}finally{clearTimeout(timer)}const data=await r.json().catch(()=>({}));if(!r.ok)return NextResponse.json({error:data?.error?.message||`WatchVault AI non disponibile (${r.status}).`},{status:r.status});const raw=extractText(data);if(!raw)return NextResponse.json({error:'WatchVault AI non ha restituito dati. Riprova con foto più nitide di quadrante e fondello.'},{status:502});let result:any;try{result=JSON.parse(raw)}catch{return NextResponse.json({error:'La risposta di WatchVault AI non era valida. Riprova.'},{status:502})}return NextResponse.json({result});}catch(e:any){if(e?.name==='AbortError')return NextResponse.json({error:'WatchVault AI ha impiegato troppo tempo. Riprova con una o due foto più leggere.'},{status:504});return NextResponse.json({error:e instanceof Error?e.message:'Errore WatchVault AI'},{status:500})}}
