'use client';
import AppShell from '@/components/AppShell';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {getSession} from '@/lib/supabase';
import {addPostComment,createCommunityPost,editCommunityPost,fetchCommunityPosts,searchPeople,toggleFollow,togglePostLike,toggleSticker} from '@/lib/community-marketplace';
import {deleteComment,editComment,enrichCommunityPosts,publicName,replyToComment} from '@/lib/social-comments';
import {fetchFriendRequests,respondFriendRequest,sendFriendRequest} from '@/lib/friends';
import {Check,Edit3,Heart,ImagePlus,MessageCircle,Reply,Search,Trash2,UserPlus,X} from 'lucide-react';
const postPhoto=(path:string)=>`${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/posts/${path}`;
const stickers=['⌚','🔥','👏','😍','💎','🤝'];
export default function Social(){
 const[posts,setPosts]=useState<any[]>([]),[body,setBody]=useState(''),[files,setFiles]=useState<File[]>([]),[previews,setPreviews]=useState<string[]>([]),[msg,setMsg]=useState(''),[show,setShow]=useState(false),[peopleQ,setPeopleQ]=useState(''),[people,setPeople]=useState<any[]>([]),[friends,setFriends]=useState<any>({incoming:[],outgoing:[],friends:[]}),[comment,setComment]=useState<Record<string,string>>({}),[reply,setReply]=useState<Record<string,string>>({}),[editing,setEditing]=useState<any>(null),[editingComment,setEditingComment]=useState<any>(null);const input=useRef<HTMLInputElement>(null);const me=getSession()?.user.id;
 async function load(){try{const[p,f]=await Promise.all([fetchCommunityPosts(),fetchFriendRequests()]);setPosts(await enrichCommunityPosts(p));setFriends(f)}catch(e){setMsg(e instanceof Error?e.message:'Errore')}}
 useEffect(()=>{load()},[]);
 async function findPeople(e:React.FormEvent){e.preventDefault();if(!peopleQ.trim())return setPeople([]);try{setPeople(await searchPeople(peopleQ))}catch(e){setMsg(e instanceof Error?e.message:'Errore')}}
 function choose(e:React.ChangeEvent<HTMLInputElement>){const fs=[...(e.target.files||[])].filter(f=>f.type.startsWith('image/')).slice(0,6);setFiles(fs);setPreviews(fs.map(URL.createObjectURL));e.target.value=''}
 async function submit(e:React.FormEvent){e.preventDefault();if(!body.trim())return;try{await createCommunityPost(body.trim(),files);previews.forEach(URL.revokeObjectURL);setBody('');setFiles([]);setPreviews([]);setShow(false);await load()}catch(e){setMsg(e instanceof Error?e.message:'Errore')}}
 async function addComment(id:string){const text=(comment[id]||'').trim();if(!text)return;await addPostComment(id,text);setComment(v=>({...v,[id]:''}));await load()}
 async function addReply(postId:string,parentId:string){const text=(reply[parentId]||'').trim();if(!text)return;await replyToComment(postId,parentId,text);setReply(v=>({...v,[parentId]:''}));await load()}
 async function saveEdit(e:React.FormEvent){e.preventDefault();await editCommunityPost(editing.id,editing.body);setEditing(null);await load()}
 async function saveCommentEdit(e:React.FormEvent){e.preventDefault();await editComment(editingComment.id,editingComment.body);setEditingComment(null);await load()}
 async function friend(userId:string){try{await sendFriendRequest(userId);setMsg('Richiesta di amicizia inviata.');await load()}catch(e){setMsg(e instanceof Error?e.message:'Errore')}}
 async function friendReply(id:string,status:'accepted'|'rejected'){await respondFriendRequest(id,status);await load()}
 const avatar=(p:any)=><div className="avatar" style={{flex:'0 0 44px',width:44,height:44,overflow:'hidden'}}>{p?.avatar_url?<img src={p.avatar_url} alt="" style={{width:'100%',height:'100%',borderRadius:'50%',objectFit:'cover'}}/>:(publicName(p)[0]||'U').toUpperCase()}</div>;
 return <AppShell><div className="pagehead"><div><div className="eyebrow">COMMUNITY REALE</div><h1>Feed dei collezionisti</h1><p className="muted page-subtitle">Condividi la passione, commenta e crea la tua rete.</p></div><button className="btn primary" onClick={()=>setShow(v=>!v)}>+ Pubblica</button></div>
 {friends.incoming?.length>0&&<section className="card" style={{marginBottom:18}}><h3>Richieste di amicizia</h3>{friends.incoming.map((r:any)=><div className="person-row" key={r.id}>{avatar(r.profiles)}<div><b>{publicName(r.profiles)}</b><div className="muted">@{r.profiles?.username}</div></div><div className="offer-actions" style={{marginLeft:'auto'}}><button className="btn primary" onClick={()=>friendReply(r.id,'accepted')}><Check size={16}/> Accetta</button><button className="btn" onClick={()=>friendReply(r.id,'rejected')}><X size={16}/> Rifiuta</button></div></div>)}</section>}
 <form className="social-tools" onSubmit={findPeople}><label className="search-box"><Search size={18}/><input placeholder="Cerca persone per username o nome…" value={peopleQ} onChange={e=>setPeopleQ(e.target.value)}/></label><button className="btn">Cerca persone</button></form>
 {people.length>0&&<div className="people-results">{people.map(p=><div className="person-row" key={p.id}>{avatar(p)}<div><b>{publicName(p)}</b><div className="muted">@{p.username}{p.city?` · ${p.city}`:''}</div></div><div className="offer-actions" style={{marginLeft:'auto'}}><button className={`btn ${p.following?'':'primary'}`} onClick={async()=>{const following=await toggleFollow(p.id);setPeople(v=>v.map(x=>x.id===p.id?{...x,following}:x))}}>{p.following?'Seguito':'Segui'}</button><button className="btn" onClick={()=>friend(p.id)}><UserPlus size={16}/> Amico</button></div></div>)}</div>}
 {show&&<form className="card feed" onSubmit={submit} style={{marginBottom:20}}><div className="field"><label>Cosa vuoi condividere?</label><textarea rows={4} maxLength={5000} value={body} onChange={e=>setBody(e.target.value)} placeholder="Parla del tuo orologio, usa @username per menzionare qualcuno…" required/></div><button type="button" className="btn" onClick={()=>input.current?.click()}><ImagePlus size={17}/> Aggiungi foto ({files.length}/6)</button><input ref={input} hidden multiple type="file" accept="image/*" onChange={choose}/>{previews.length>0&&<div className="photo-strip">{previews.map((p,i)=><div className="photo-thumb" key={p}><img src={p} alt=""/><button type="button" onClick={()=>{URL.revokeObjectURL(p);setPreviews(v=>v.filter((_,x)=>x!==i));setFiles(v=>v.filter((_,x)=>x!==i))}}><X size={14}/></button></div>)}</div>}<div className="form-actions"><button type="button" className="btn" onClick={()=>setShow(false)}>Annulla</button><button className="btn primary">Pubblica</button></div></form>}
 {msg&&<p className="form-message">{msg}</p>}
 <div className="feed">{posts.map(p=>{const liked=p.likes?.some((x:any)=>x.user_id===me);const roots=(p.comments||[]).filter((c:any)=>!c.parent_id);return <article className="post" key={p.id}><div className="post-user">{avatar(p.profiles)}<div><Link href={`/profile?user=${p.author_id}`} style={{color:'inherit',textDecoration:'none'}}><b>{publicName(p.profiles)}</b></Link><div className="muted">{new Date(p.created_at).toLocaleString('it-IT')}{p.edited_at&&<span className="edited-label"> · modificato</span>}</div></div>{p.author_id===me&&<button className="icon-btn" style={{marginLeft:'auto'}} onClick={()=>setEditing({...p})}><Edit3 size={16}/></button>}</div><p>{p.body}</p>{p.images?.length>0&&<div className="post-photo-strip">{p.images.map((im:any)=><img key={im.id} src={postPhoto(im.storage_path)} alt="post community"/>)}</div>}<div className="post-actions"><button className={liked?'active':''} onClick={async()=>{await togglePostLike(p.id);await load()}}><Heart size={18}/>{p.likes?.length||0}</button><button onClick={()=>document.getElementById(`comment-${p.id}`)?.focus()}><MessageCircle size={18}/>{p.comments?.length||0}</button><span className="sticker-bar">{stickers.map(s=><button key={s} onClick={async()=>{await toggleSticker(p.id,s);await load()}}>{s} {p.reactions?.filter((r:any)=>r.sticker===s).length||''}</button>)}</span></div>
 <div className="post-comments">{roots.map((c:any)=>{const children=(p.comments||[]).filter((x:any)=>x.parent_id===c.id);const render=(x:any,child=false)=><div key={x.id} className="comment-row" style={{display:'grid',gridTemplateColumns:'38px minmax(0,1fr)',gap:10,alignItems:'start',marginLeft:child?34:0,padding:'10px 0'}}>{<div className="avatar" style={{width:38,height:38,overflow:'hidden'}}>{x.profiles?.avatar_url?<img src={x.profiles.avatar_url} alt="" style={{width:'100%',height:'100%',borderRadius:'50%',objectFit:'cover'}}/>:(publicName(x.profiles)[0]||'U')}</div>}<div style={{minWidth:0}}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><b>{publicName(x.profiles)}</b><span className="muted" style={{fontSize:12}}>{new Date(x.created_at).toLocaleString('it-IT')}{x.edited_at?' · modificato':''}</span>{x.author_id===me&&!x.deleted_at&&<><button className="icon-btn" onClick={()=>setEditingComment({...x})}><Edit3 size={13}/></button><button className="icon-btn" onClick={async()=>{if(confirm('Eliminare questo commento?')){await deleteComment(x.id);await load()}}}><Trash2 size={13}/></button></>}</div><p style={{margin:'4px 0 6px',overflowWrap:'anywhere'}}>{x.body}</p>{!x.deleted_at&&<button className="btn" style={{padding:'4px 8px',fontSize:12}} onClick={()=>setReply(v=>({...v,[x.id]:v[x.id]??''}))}><Reply size={13}/> Rispondi</button>}{reply[x.id]!==undefined&&<div style={{display:'flex',gap:6,marginTop:7}}><input style={{flex:1}} placeholder={`Rispondi a ${publicName(x.profiles)}…`} value={reply[x.id]} onChange={e=>setReply(v=>({...v,[x.id]:e.target.value}))} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addReply(p.id,x.id)}}}/><button className="btn primary" onClick={()=>addReply(p.id,x.id)}>Invia</button></div>}</div></div>;return <div key={c.id}>{render(c)}{children.map((x:any)=>render(x,true))}</div>})}</div>
 <div className="field"><input id={`comment-${p.id}`} placeholder="Scrivi un commento…" value={comment[p.id]||''} onChange={e=>setComment(v=>({...v,[p.id]:e.target.value}))} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addComment(p.id)}}}/></div></article>})}</div>
 {editing&&<div className="modal-backdrop"><form className="watch-form" onSubmit={saveEdit}><div className="form-title"><h2>Modifica post</h2><button type="button" className="icon-btn" onClick={()=>setEditing(null)}><X/></button></div><div className="field"><textarea rows={6} value={editing.body} onChange={e=>setEditing({...editing,body:e.target.value})}/></div><button className="btn primary">Salva modifica</button></form></div>}
 {editingComment&&<div className="modal-backdrop"><form className="watch-form" onSubmit={saveCommentEdit}><div className="form-title"><h2>Modifica commento</h2><button type="button" className="icon-btn" onClick={()=>setEditingComment(null)}><X/></button></div><div className="field"><textarea rows={4} value={editingComment.body} onChange={e=>setEditingComment({...editingComment,body:e.target.value})}/></div><button className="btn primary">Salva</button></form></div>}
 </AppShell>}
